export const samplePosts = [
  {
    id: '1',
    user: {
      id: 'user1',
      name: 'Kristine',
      avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    },
    media: {
      id: 'media1',
      title: 'HARRY POTTER AND THE SORCERER\'S STONE',
      type: 'movie',
      progress: '@ 30:34',
      cover: 'https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg',
    },
    date: 'September 10',
    title: 'Optional Post Title',
    contentType: 'image' as const,
    content: 'https://i.redd.it/enjoy-these-memes-i-have-accumulated-v0-gb6iosdq1zva1.jpg?width=640&format=pjpg&auto=webp&s=9f48ed18e3033d865815534bea65985d9a2b5248',
    likeCount: 5,
    commentCount: 3,
    isBookmarked: false,
    isLiked: false,
  },
  {
    id: '2',
    user: {
      id: 'user2',
      name: 'Kristine',
      avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    },
    media: {
      id: 'media2',
      title: 'GILMORE GIRLS',
      type: 'show',
      progress: '@ S1E4',
      cover: 'https://m.media-amazon.com/images/M/MV5BYjEzMjM5MTktZmNkZS00MjI0LWJjMDUtYmNkOTI3MTlmODYzXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg',
    },
    date: 'September 10',
    title: 'Optional Post Title',
    contentType: 'text' as const,
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it?',
    likeCount: 12,
    commentCount: 3,
    isBookmarked: false,
    isLiked: false,
  },
  {
    id: '3',
    user: {
      id: 'user3',
      name: 'Alex',
      avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    media: {
      id: 'media3',
      title: 'THE GREAT GATSBY',
      type: 'book',
      progress: 'page 45',
      cover: 'https://m.media-amazon.com/images/I/81QuEGw8VPL._AC_UF1000,1000_QL80_.jpg',
    },
    date: 'September 9',
    title: 'Thoughts on Chapter 3',
    contentType: 'mixed' as const,
    content: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500',
    textContent: 'The symbolism in this chapter is incredible. Fitzgerald really knows how to paint a picture with words. The green light continues to be such a powerful metaphor.',
    likeCount: 8,
    commentCount: 5,
    isBookmarked: false,
    isLiked: false,
  },
];
